apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: tennis-ml

servers: 1
agents: 0

volumes:
  - volume: prefect-data:/var/lib/rancher/k3s/storage
    nodeFilters:
      - server:0

ports:
  - port: 4200:30420
    nodeFilters:
      - server:0:direct

options:
  k3d:
    wait: true
    timeout: "120s"
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
