apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: tennis-ml

servers: 1
agents: 0

network: tennis-ml-net

registries:
  create:
    name: tennis-ml-registry
    host: "0.0.0.0"
    hostPort: "5000"

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "120s"
