alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d

prometheus-adapter:
  enabled: false

grafana:
  enabled: true
  plugins:
    - grafana-clickhouse-datasource
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
    - name: ClickHouse
      type: grafana-clickhouse-datasource
      access: proxy
      url: http://clickhouse:8123
      jsonData:
        defaultDatabase: gold
        protocol: http
