apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: mlflow.macsteve.lan
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mlflow
                port:
                  number: 5000
    - host: prefect.macsteve.lan
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: prefect-server
                port:
                  number: 4200
    - host: clickhouse.macsteve.lan
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: clickhouse
                port:
                  number: 8123
