apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.20.2
          args:
            - mlflow
            - server
            - --host
            - "0.0.0.0"
            - --port
            - "5000"
            - --backend-store-uri
            - sqlite:///data/mlflow.db
            - --default-artifact-root
            - /data/artifacts
            - --serve-artifacts

          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: tennis-default-config
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 120
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-data
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  ports:
    - name: http
      port: 5000
      targetPort: http
  selector:
    app: mlflow
