apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    additionalArguments:
      - --providers.kubernetesingress.allowExternalNameServices=true
      - --providers.kubernetescrd.allowExternalNameServices=true
